service: user-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
